server.port=3000
server.tomcat.threads.max=200
logging.level.org.springframework.security=INFO
#logging.level.org.springframework.security.oauth2=TRACE

#spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/postgres?createDatabaseIfNotExist=true
#spring.datasource.username=postgres
#spring.datasource.password=postgres13
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

app.gemini.apiKey=AIzaSyCLfy9xurU2wWGL4U4WihEK6ZG8N9g_CDc
#app.gemini.model=gemini-2.5-flash
app.gemini.model=gemini-2.5-pro
app.sftp.host=3.21.164.7
app.sftp.port=22
app.sftp.username=usuario1
app.sftp.password=usuario1
app.sftp.privateKey=